alter table public.agent_messages
  add column if not exists message_order bigint generated by default as identity;

drop index if exists public.idx_agent_messages_conversation_created;
create index if not exists idx_agent_messages_conversation_order
  on public.agent_messages (conversation_id, message_order);
