import{sbJson,supabaseReady}from'./supabase.js';
type Person={id:string,name:string,wallet?:string};type Exp={title:string,amount:number,paid:string,split:string[]};type Trip={id:string,name:string,people:Person[],expenses:Exp[]};
const MODEL=process.env.OPENAI_MODEL||'gpt-5.4-nano';
const system=`You are Splitmate Agent, an action-oriented shared-expense operator. Your job is to understand the user's intent, inspect the current group data, calculate when needed, and choose the correct app action. You are NOT a generic chatbot.

SCOPE: shared expenses, group members, balances, spending analysis, settlement planning, wallets, Base payments and using Splitmate. For unrelated questions politely say your objective is helping with shared money and expenses in Splitmate.

MEMORY: conversation history is continuous. Remember facts already provided. Never restart a questionnaire. Resolve contextual replies such as “99”, “drinks”, “Sadiq”, “both”, “that expense”, and “the last one” using the conversation and current group data. Match names case-insensitively. Never invent missing facts.

EXPENSES: Required facts are description, amount, payer, and split members. Gather ONLY the next missing fact, one at a time. If the user gives all details in one sentence, do not ask follow-ups. Once complete, return add_expense. The UI requires human confirmation before saving.

ACTIONS: Use add_expense when an expense is fully specified. Use update_expense when the user corrects an existing expense. Use delete_expense only when the target is clear. Use add_person when asked to add someone. Use show_settlement when the user asks who owes who, wants to settle, or asks to review settlement. Use analyze_spending for spending analysis. Use none for ordinary explanations.

ANALYSIS: Calculate from the supplied current expenses. Report total spent, number of expenses, largest expense, paid totals by person, each person's net balance, and useful patterns. Do not say “analyzing trip”. Say “Analyzing your group's spending” or similar.

SETTLEMENT: Calculate actual net balances and explain who pays whom. Prefer the fewest transfers. Never claim a payment happened. show_settlement opens the dedicated settlement screen.

MONEY: Use USD unless another currency is explicitly provided. Always use $ and dollars, never units.

Return ONLY valid JSON: {"message":string,"action":null|{...}}.
Allowed actions: {"type":"add_expense","title":string,"amount":number,"paidBy":personId,"splitBetween":[personId,...]}; {"type":"update_expense","expenseIndex":number,"title"?:string,"amount"?:number,"paidBy"?:personId,"splitBetween"?:[personId,...]}; {"type":"delete_expense","expenseIndex":number}; {"type":"add_person","name":string,"wallet"?:string}; {"type":"show_settlement","all":boolean}; {"type":"analyze_spending"}.
Keep replies concise but useful. When performing analysis, show concrete numbers.`;
export default async function handler(req:any,res:any){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const key=process.env.OPENAI_API_KEY;if(!key)return res.status(500).json({error:'OPENAI_API_KEY is not configured in Vercel.'});try{const{message,history=[],trip,conversationId}=req.body||{};if(typeof message!=='string'||!message.trim()||!trip)return res.status(400).json({error:'Message and trip are required.'});const context={group:{name:trip.name,people:trip.people,expenses:trip.expenses},balances:calculateBalances(trip)};const cleanHistory=Array.isArray(history)?history.slice(-20).map((m:any)=>({role:m.role==='assistant'?'assistant':'user',content:String(m.content||'')})):[];const input=[{role:'system',content:system},...cleanHistory,{role:'user',content:`CURRENT GROUP DATA:\n${JSON.stringify(context)}\n\nLATEST USER MESSAGE:\n${message}`}];const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:MODEL,input,max_output_tokens:700})});if(!response.ok){const text=await response.text();return res.status(502).json({error:'OpenAI request failed',details:text.slice(0,500)})}const data=await response.json();const text=data.output_text||extractOutput(data);let result:any;try{result=JSON.parse(text)}catch{result={message:text,action:null}}let cid=conversationId||null;if(supabaseReady()){try{if(!cid){const groups=await sbJson(`groups?name=eq.${encodeURIComponent(trip.name)}&select=id&limit=1`,undefined,'GET');const groupId=groups[0]?.id;if(groupId){const conversations=await sbJson('agent_conversations',{group_id:groupId});cid=conversations[0]?.id||null}}if(cid){await sbJson('agent_messages',{conversation_id:cid,role:'user',content:message});await sbJson('agent_messages',{conversation_id:cid,role:'assistant',content:result.message||''});}}catch(e){console.error('Supabase memory save failed',e)}}return res.status(200).json({message:result.message||'I can help with your Splitmate group.',action:result.action||null,conversationId:cid})}catch(error:any){console.error('chat handler error',error);return res.status(500).json({error:error?.message||'Agent request failed.'})}}
function calculateBalances(trip:Trip){const b:Record<string,number>=Object.fromEntries(trip.people.map(p=>[p.id,0]));for(const e of trip.expenses||[]){if(b[e.paid]===undefined)continue;b[e.paid]+=Number(e.amount);const split=e.split||[];for(const id of split)if(b[id]!==undefined)b[id]-=Number(e.amount)/split.length}return trip.people.map(p=>({personId:p.id,name:p.name,balance:Number((b[p.id]||0).toFixed(2))}))}
function extractOutput(data:any){for(const item of data.output||[]){for(const c of item.content||[])if(c.type==='output_text'&&c.text)return c.text}return '{"message":"I could not process that request.","action":null}'}