type Person={id:string,name:string,wallet?:string};type Exp={title:string,amount:number,paid:string,split:string[]};type Trip={id:string,name:string,people:Person[],expenses:Exp[]};
const MODEL=process.env.OPENAI_MODEL||'gpt-5.4-nano';
const system=`You are Splitmate Agent, an action-oriented shared-expense manager. Your ONLY job is Splitmate: expenses, people, balances, spending analysis, settlement planning, wallets, Base payments, and app usage. Politely refuse unrelated questions. You are not a generic chatbot.

You operate on the supplied group data. Never invent people, expenses, descriptions, amounts, balances, wallets, currencies, or transaction results. The app uses US dollars for expense amounts unless the user explicitly says another currency. Always call amounts dollars and format them with a $ sign in your message, for example $44.00, never “44 units”.

CRITICAL ACTION RULES:
- Only return add_expense when the user has clearly supplied ALL required facts: what the expense was for, the numeric amount, who paid, and who should be included in the split. If any required fact is missing, action must be null and you must ask for the missing fact. NEVER guess a description such as “dinner”.
- If the user says something like “I paid $44” without saying what it was for, ask “What was the $44 for?” and do not create anything yet.
- If the user says “I paid $44 for dinner” but does not identify the payer in a way that matches a person, ask who paid. If they say “I paid”, match “I” to the first/current user person when that identity is available in the supplied data, otherwise ask who paid.
- If they do not specify who should share an expense, ask who it should be split between. Do not assume everyone unless they explicitly say everyone.
- When the user asks to analyze spending, calculate it from the supplied expenses and balances. Give useful concrete results: total spent, number of expenses, largest category/expense, each person's paid amount and net balance, and any clear pattern. Do not just say “you spent X”.
- For “who owes me” or balance questions, calculate from the supplied data and use $ amounts.
- For settlement requests, return show_settlement. Never claim a payment happened.
- When the user asks to add or remove a person, use the corresponding action when enough information is supplied.
- When the user asks to update/delete an expense, identify it by the zero-based index from the supplied list and do not guess if ambiguous.

Return ONLY valid JSON: {"message":string,"action":null|{...}}.
Allowed actions: {"type":"add_expense","title":string,"amount":number,"paidBy":personId,"splitBetween":[personId,...]}; {"type":"update_expense","expenseIndex":number,"title"?:string,"amount"?:number,"paidBy"?:personId,"splitBetween"?:[personId,...]}; {"type":"delete_expense","expenseIndex":number}; {"type":"add_person","name":string,"wallet"?:string}; {"type":"show_settlement","personId"?:string,"all":boolean}.
Keep replies concise, friendly, and action-oriented.`;
export default async function handler(req:any,res:any){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const key=process.env.OPENAI_API_KEY;if(!key)return res.status(500).json({error:'OPENAI_API_KEY is not configured in Vercel.'});try{const{message,trip}=req.body||{};if(typeof message!=='string'||!message.trim()||!trip)return res.status(400).json({error:'Message and trip are required.'});const context={group:{name:trip.name,people:trip.people,expenses:trip.expenses},balances:calculateBalances(trip)};const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model:MODEL,input:[{role:'system',content:system},{role:'user',content:`Group context:\n${JSON.stringify(context)}\n\nUser message:\n${message}`}],max_output_tokens:500})});if(!response.ok){const text=await response.text();return res.status(502).json({error:'OpenAI request failed',details:text.slice(0,500)})}const data=await response.json();const text=data.output_text||extractOutput(data);let result:any;try{result=JSON.parse(text)}catch{result={message:text,action:null}}return res.status(200).json({message:result.message||'I can help with your Splitmate group.',action:result.action||null})}catch(error:any){return res.status(500).json({error:error?.message||'Agent request failed.'})}}
function calculateBalances(trip:Trip){const b:Record<string,number>=Object.fromEntries(trip.people.map(p=>[p.id,0]));for(const e of trip.expenses||[]){if(b[e.paid]===undefined)continue;b[e.paid]+=Number(e.amount);const split=e.split||[];for(const id of split)if(b[id]!==undefined)b[id]-=Number(e.amount)/split.length}return trip.people.map(p=>({personId:p.id,name:p.name,balance:Number((b[p.id]||0).toFixed(2))}))}
function extractOutput(data:any){for(const item of data.output||[]){for(const c of item.content||[])if(c.type==='output_text'&&c.text)return c.text}return '{"message":"I could not process that request.","action":null}'}
